-- cree tables reference pays departement civilite
-- depends: 0001.cree-table-utilisateur

-- Trois tables de référence figées par des standards externes (ISO pour les
-- pays, INSEE pour les départements) ou par un vocabulaire professionnel
-- restreint (civilités). Contrairement aux rôles métier, elles n'ont pas
-- vocation à être étendues par l'usage du cabinet au jour le jour.

CREATE TABLE pays (
    code_iso char(2) PRIMARY KEY,
    libelle text NOT NULL,
    gentile_masculin text,
    gentile_feminin text
);

CREATE TABLE departement (
    code text PRIMARY KEY,
    libelle text NOT NULL
);

CREATE TABLE civilite (
    code text PRIMARY KEY,
    libelle text NOT NULL,
    abreviation text
);

INSERT INTO pays (code_iso, libelle, gentile_masculin, gentile_feminin) VALUES
    ('AF', 'Afghanistan', 'Afghan', 'Afghane'),
    ('ZA', 'Afrique du Sud', 'Sud-Africain', 'Sud-Africaine'),
    ('AL', 'Albanie', 'Albanais', 'Albanaise'),
    ('DZ', 'Algérie', 'Algérien', 'Algérienne'),
    ('DE', 'Allemagne', 'Allemand', 'Allemande'),
    ('AD', 'Andorre', 'Andorran', 'Andorrane'),
    ('AO', 'Angola', 'Angolais', 'Angolaise'),
    ('AG', 'Antigua-et-Barbuda', 'Antiguayais', 'Antiguayaise'),
    ('SA', 'Arabie saoudite', 'Saoudien', 'Saoudienne'),
    ('AR', 'Argentine', 'Argentin', 'Argentine'),
    ('AM', 'Arménie', 'Arménien', 'Arménienne'),
    ('AU', 'Australie', 'Australien', 'Australienne'),
    ('AT', 'Autriche', 'Autrichien', 'Autrichienne'),
    ('AZ', 'Azerbaïdjan', 'Azerbaïdjanais', 'Azerbaïdjanaise'),
    ('BS', 'Bahamas', 'Bahamien', 'Bahamienne'),
    ('BH', 'Bahreïn', 'Bahreïni', 'Bahreïnie'),
    ('BD', 'Bangladesh', 'Bangladais', 'Bangladaise'),
    ('BB', 'Barbade', 'Barbadien', 'Barbadienne'),
    ('BE', 'Belgique', 'Belge', 'Belge'),
    ('BZ', 'Belize', 'Belizien', 'Belizienne'),
    ('BJ', 'Bénin', 'Béninois', 'Béninoise'),
    ('BT', 'Bhoutan', 'Bhoutanais', 'Bhoutanaise'),
    ('BY', 'Biélorussie', 'Biélorusse', 'Biélorusse'),
    ('MM', 'Birmanie', 'Birman', 'Birmane'),
    ('BO', 'Bolivie', 'Bolivien', 'Bolivienne'),
    ('BA', 'Bosnie-Herzégovine', 'Bosnien', 'Bosnienne'),
    ('BW', 'Botswana', 'Botswanais', 'Botswanaise'),
    ('BR', 'Brésil', 'Brésilien', 'Brésilienne'),
    ('BN', 'Brunei', 'Brunéien', 'Brunéienne'),
    ('BG', 'Bulgarie', 'Bulgare', 'Bulgare'),
    ('BF', 'Burkina Faso', 'Burkinabé', 'Burkinabée'),
    ('BI', 'Burundi', 'Burundais', 'Burundaise'),
    ('KH', 'Cambodge', 'Cambodgien', 'Cambodgienne'),
    ('CM', 'Cameroun', 'Camerounais', 'Camerounaise'),
    ('CA', 'Canada', 'Canadien', 'Canadienne'),
    ('CV', 'Cap-Vert', 'Cap-verdien', 'Cap-verdienne'),
    ('CF', 'République centrafricaine', 'Centrafricain', 'Centrafricaine'),
    ('CL', 'Chili', 'Chilien', 'Chilienne'),
    ('CN', 'Chine', 'Chinois', 'Chinoise'),
    ('CY', 'Chypre', 'Chypriote', 'Chypriote'),
    ('CO', 'Colombie', 'Colombien', 'Colombienne'),
    ('KM', 'Comores', 'Comorien', 'Comorienne'),
    ('CG', 'Congo', 'Congolais', 'Congolaise'),
    ('CD', 'République démocratique du Congo', 'Congolais', 'Congolaise'),
    ('KR', 'Corée du Sud', 'Sud-Coréen', 'Sud-Coréenne'),
    ('KP', 'Corée du Nord', 'Nord-Coréen', 'Nord-Coréenne'),
    ('CR', 'Costa Rica', 'Costaricien', 'Costaricienne'),
    ('CI', 'Côte d''Ivoire', 'Ivoirien', 'Ivoirienne'),
    ('HR', 'Croatie', 'Croate', 'Croate'),
    ('CU', 'Cuba', 'Cubain', 'Cubaine'),
    ('DK', 'Danemark', 'Danois', 'Danoise'),
    ('DJ', 'Djibouti', 'Djiboutien', 'Djiboutienne'),
    ('DM', 'Dominique', 'Dominiquais', 'Dominiquaise'),
    ('EG', 'Égypte', 'Égyptien', 'Égyptienne'),
    ('AE', 'Émirats arabes unis', 'Émirien', 'Émirienne'),
    ('EC', 'Équateur', 'Équatorien', 'Équatorienne'),
    ('ER', 'Érythrée', 'Érythréen', 'Érythréenne'),
    ('ES', 'Espagne', 'Espagnol', 'Espagnole'),
    ('EE', 'Estonie', 'Estonien', 'Estonienne'),
    ('SZ', 'Eswatini', 'Swazi', 'Swazie'),
    ('US', 'États-Unis', 'Américain', 'Américaine'),
    ('ET', 'Éthiopie', 'Éthiopien', 'Éthiopienne'),
    ('FJ', 'Fidji', 'Fidjien', 'Fidjienne'),
    ('FI', 'Finlande', 'Finlandais', 'Finlandaise'),
    ('FR', 'France', 'Français', 'Française'),
    ('GA', 'Gabon', 'Gabonais', 'Gabonaise'),
    ('GM', 'Gambie', 'Gambien', 'Gambienne'),
    ('GE', 'Géorgie', 'Géorgien', 'Géorgienne'),
    ('GH', 'Ghana', 'Ghanéen', 'Ghanéenne'),
    ('GR', 'Grèce', 'Grec', 'Grecque'),
    ('GD', 'Grenade', 'Grenadien', 'Grenadienne'),
    ('GT', 'Guatemala', 'Guatémaltèque', 'Guatémaltèque'),
    ('GN', 'Guinée', 'Guinéen', 'Guinéenne'),
    ('GQ', 'Guinée équatoriale', 'Équatoguinéen', 'Équatoguinéenne'),
    ('GW', 'Guinée-Bissau', 'Bissau-guinéen', 'Bissau-guinéenne'),
    ('GY', 'Guyana', 'Guyanien', 'Guyanienne'),
    ('HT', 'Haïti', 'Haïtien', 'Haïtienne'),
    ('HN', 'Honduras', 'Hondurien', 'Hondurienne'),
    ('HU', 'Hongrie', 'Hongrois', 'Hongroise'),
    ('IN', 'Inde', 'Indien', 'Indienne'),
    ('ID', 'Indonésie', 'Indonésien', 'Indonésienne'),
    ('IQ', 'Irak', 'Irakien', 'Irakienne'),
    ('IR', 'Iran', 'Iranien', 'Iranienne'),
    ('IE', 'Irlande', 'Irlandais', 'Irlandaise'),
    ('IS', 'Islande', 'Islandais', 'Islandaise'),
    ('IL', 'Israël', 'Israélien', 'Israélienne'),
    ('IT', 'Italie', 'Italien', 'Italienne'),
    ('JM', 'Jamaïque', 'Jamaïcain', 'Jamaïcaine'),
    ('JP', 'Japon', 'Japonais', 'Japonaise'),
    ('JO', 'Jordanie', 'Jordanien', 'Jordanienne'),
    ('KZ', 'Kazakhstan', 'Kazakh', 'Kazakhe'),
    ('KE', 'Kenya', 'Kényan', 'Kényane'),
    ('KG', 'Kirghizistan', 'Kirghize', 'Kirghize'),
    ('KI', 'Kiribati', 'Kiribatien', 'Kiribatienne'),
    ('KW', 'Koweït', 'Koweïtien', 'Koweïtienne'),
    ('LA', 'Laos', 'Laotien', 'Laotienne'),
    ('LS', 'Lesotho', 'Lesothan', 'Lesothane'),
    ('LV', 'Lettonie', 'Letton', 'Lettone'),
    ('LB', 'Liban', 'Libanais', 'Libanaise'),
    ('LR', 'Liberia', 'Libérien', 'Libérienne'),
    ('LY', 'Libye', 'Libyen', 'Libyenne'),
    ('LI', 'Liechtenstein', 'Liechtensteinois', 'Liechtensteinoise'),
    ('LT', 'Lituanie', 'Lituanien', 'Lituanienne'),
    ('LU', 'Luxembourg', 'Luxembourgeois', 'Luxembourgeoise'),
    ('MK', 'Macédoine du Nord', 'Macédonien', 'Macédonienne'),
    ('MG', 'Madagascar', 'Malgache', 'Malgache'),
    ('MY', 'Malaisie', 'Malaisien', 'Malaisienne'),
    ('MW', 'Malawi', 'Malawite', 'Malawite'),
    ('MV', 'Maldives', 'Maldivien', 'Maldivienne'),
    ('ML', 'Mali', 'Malien', 'Malienne'),
    ('MT', 'Malte', 'Maltais', 'Maltaise'),
    ('MA', 'Maroc', 'Marocain', 'Marocaine'),
    ('MH', 'Îles Marshall', 'Marshallais', 'Marshallaise'),
    ('MU', 'Maurice', 'Mauricien', 'Mauricienne'),
    ('MR', 'Mauritanie', 'Mauritanien', 'Mauritanienne'),
    ('MX', 'Mexique', 'Mexicain', 'Mexicaine'),
    ('FM', 'Micronésie', 'Micronésien', 'Micronésienne'),
    ('MD', 'Moldavie', 'Moldave', 'Moldave'),
    ('MC', 'Monaco', 'Monégasque', 'Monégasque'),
    ('MN', 'Mongolie', 'Mongol', 'Mongole'),
    ('ME', 'Monténégro', 'Monténégrin', 'Monténégrine'),
    ('MZ', 'Mozambique', 'Mozambicain', 'Mozambicaine'),
    ('NA', 'Namibie', 'Namibien', 'Namibienne'),
    ('NR', 'Nauru', 'Nauruan', 'Nauruane'),
    ('NP', 'Népal', 'Népalais', 'Népalaise'),
    ('NI', 'Nicaragua', 'Nicaraguayen', 'Nicaraguayenne'),
    ('NE', 'Niger', 'Nigérien', 'Nigérienne'),
    ('NG', 'Nigeria', 'Nigérian', 'Nigériane'),
    ('NO', 'Norvège', 'Norvégien', 'Norvégienne'),
    ('NZ', 'Nouvelle-Zélande', 'Néo-Zélandais', 'Néo-Zélandaise'),
    ('OM', 'Oman', 'Omanais', 'Omanaise'),
    ('UG', 'Ouganda', 'Ougandais', 'Ougandaise'),
    ('UZ', 'Ouzbékistan', 'Ouzbek', 'Ouzbèke'),
    ('PK', 'Pakistan', 'Pakistanais', 'Pakistanaise'),
    ('PW', 'Palaos', 'Palaosien', 'Palaosienne'),
    ('PA', 'Panama', 'Panaméen', 'Panaméenne'),
    ('PG', 'Papouasie-Nouvelle-Guinée', 'Papouasien', 'Papouasienne'),
    ('PY', 'Paraguay', 'Paraguayen', 'Paraguayenne'),
    ('NL', 'Pays-Bas', 'Néerlandais', 'Néerlandaise'),
    ('PE', 'Pérou', 'Péruvien', 'Péruvienne'),
    ('PH', 'Philippines', 'Philippin', 'Philippine'),
    ('PL', 'Pologne', 'Polonais', 'Polonaise'),
    ('PT', 'Portugal', 'Portugais', 'Portugaise'),
    ('QA', 'Qatar', 'Qatari', 'Qatarienne'),
    ('RO', 'Roumanie', 'Roumain', 'Roumaine'),
    ('GB', 'Royaume-Uni', 'Britannique', 'Britannique'),
    ('RU', 'Russie', 'Russe', 'Russe'),
    ('RW', 'Rwanda', 'Rwandais', 'Rwandaise'),
    ('KN', 'Saint-Christophe-et-Niévès', 'Kittitien', 'Kittitienne'),
    ('SM', 'Saint-Marin', 'Saint-Marinais', 'Saint-Marinaise'),
    ('VC', 'Saint-Vincent-et-les-Grenadines', 'Vincentais', 'Vincentaise'),
    ('LC', 'Sainte-Lucie', 'Saint-Lucien', 'Saint-Lucienne'),
    ('SB', 'Îles Salomon', 'Salomonais', 'Salomonaise'),
    ('SV', 'Salvador', 'Salvadorien', 'Salvadorienne'),
    ('WS', 'Samoa', 'Samoan', 'Samoane'),
    ('ST', 'Sao Tomé-et-Principe', 'Santoméen', 'Santoméenne'),
    ('SN', 'Sénégal', 'Sénégalais', 'Sénégalaise'),
    ('RS', 'Serbie', 'Serbe', 'Serbe'),
    ('SC', 'Seychelles', 'Seychellois', 'Seychelloise'),
    ('SL', 'Sierra Leone', 'Sierra-Léonais', 'Sierra-Léonaise'),
    ('SG', 'Singapour', 'Singapourien', 'Singapourienne'),
    ('SK', 'Slovaquie', 'Slovaque', 'Slovaque'),
    ('SI', 'Slovénie', 'Slovène', 'Slovène'),
    ('SO', 'Somalie', 'Somalien', 'Somalienne'),
    ('SD', 'Soudan', 'Soudanais', 'Soudanaise'),
    ('SS', 'Soudan du Sud', 'Sud-Soudanais', 'Sud-Soudanaise'),
    ('LK', 'Sri Lanka', 'Sri-Lankais', 'Sri-Lankaise'),
    ('SE', 'Suède', 'Suédois', 'Suédoise'),
    ('CH', 'Suisse', 'Suisse', 'Suissesse'),
    ('SR', 'Suriname', 'Surinamais', 'Surinamaise'),
    ('SY', 'Syrie', 'Syrien', 'Syrienne'),
    ('TJ', 'Tadjikistan', 'Tadjik', 'Tadjike'),
    ('TZ', 'Tanzanie', 'Tanzanien', 'Tanzanienne'),
    ('TD', 'Tchad', 'Tchadien', 'Tchadienne'),
    ('CZ', 'Tchéquie', 'Tchèque', 'Tchèque'),
    ('TH', 'Thaïlande', 'Thaïlandais', 'Thaïlandaise'),
    ('TL', 'Timor oriental', 'Timorais', 'Timoraise'),
    ('TG', 'Togo', 'Togolais', 'Togolaise'),
    ('TO', 'Tonga', 'Tongien', 'Tongienne'),
    ('TT', 'Trinité-et-Tobago', 'Trinidadien', 'Trinidadienne'),
    ('TN', 'Tunisie', 'Tunisien', 'Tunisienne'),
    ('TM', 'Turkménistan', 'Turkmène', 'Turkmène'),
    ('TR', 'Turquie', 'Turc', 'Turque'),
    ('TV', 'Tuvalu', 'Tuvaluan', 'Tuvaluane'),
    ('UA', 'Ukraine', 'Ukrainien', 'Ukrainienne'),
    ('UY', 'Uruguay', 'Uruguayen', 'Uruguayenne'),
    ('VU', 'Vanuatu', 'Vanuatais', 'Vanuataise'),
    ('VA', 'Vatican', 'Vatican', 'Vaticane'),
    ('VE', 'Venezuela', 'Vénézuélien', 'Vénézuélienne'),
    ('VN', 'Vietnam', 'Vietnamien', 'Vietnamienne'),
    ('YE', 'Yémen', 'Yéménite', 'Yéménite'),
    ('ZM', 'Zambie', 'Zambien', 'Zambienne'),
    ('ZW', 'Zimbabwe', 'Zimbabwéen', 'Zimbabwéenne');

INSERT INTO departement (code, libelle) VALUES
    ('01', 'Ain'), ('02', 'Aisne'), ('03', 'Allier'), ('04', 'Alpes-de-Haute-Provence'),
    ('05', 'Hautes-Alpes'), ('06', 'Alpes-Maritimes'), ('07', 'Ardèche'), ('08', 'Ardennes'),
    ('09', 'Ariège'), ('10', 'Aube'), ('11', 'Aude'), ('12', 'Aveyron'),
    ('13', 'Bouches-du-Rhône'), ('14', 'Calvados'), ('15', 'Cantal'), ('16', 'Charente'),
    ('17', 'Charente-Maritime'), ('18', 'Cher'), ('19', 'Corrèze'), ('2A', 'Corse-du-Sud'),
    ('2B', 'Haute-Corse'), ('21', 'Côte-d''Or'), ('22', 'Côtes-d''Armor'), ('23', 'Creuse'),
    ('24', 'Dordogne'), ('25', 'Doubs'), ('26', 'Drôme'), ('27', 'Eure'),
    ('28', 'Eure-et-Loir'), ('29', 'Finistère'), ('30', 'Gard'), ('31', 'Haute-Garonne'),
    ('32', 'Gers'), ('33', 'Gironde'), ('34', 'Hérault'), ('35', 'Ille-et-Vilaine'),
    ('36', 'Indre'), ('37', 'Indre-et-Loire'), ('38', 'Isère'), ('39', 'Jura'),
    ('40', 'Landes'), ('41', 'Loir-et-Cher'), ('42', 'Loire'), ('43', 'Haute-Loire'),
    ('44', 'Loire-Atlantique'), ('45', 'Loiret'), ('46', 'Lot'), ('47', 'Lot-et-Garonne'),
    ('48', 'Lozère'), ('49', 'Maine-et-Loire'), ('50', 'Manche'), ('51', 'Marne'),
    ('52', 'Haute-Marne'), ('53', 'Mayenne'), ('54', 'Meurthe-et-Moselle'), ('55', 'Meuse'),
    ('56', 'Morbihan'), ('57', 'Moselle'), ('58', 'Nièvre'), ('59', 'Nord'),
    ('60', 'Oise'), ('61', 'Orne'), ('62', 'Pas-de-Calais'), ('63', 'Puy-de-Dôme'),
    ('64', 'Pyrénées-Atlantiques'), ('65', 'Hautes-Pyrénées'), ('66', 'Pyrénées-Orientales'), ('67', 'Bas-Rhin'),
    ('68', 'Haut-Rhin'), ('69', 'Rhône'), ('70', 'Haute-Saône'), ('71', 'Saône-et-Loire'),
    ('72', 'Sarthe'), ('73', 'Savoie'), ('74', 'Haute-Savoie'), ('75', 'Paris'),
    ('76', 'Seine-Maritime'), ('77', 'Seine-et-Marne'), ('78', 'Yvelines'), ('79', 'Deux-Sèvres'),
    ('80', 'Somme'), ('81', 'Tarn'), ('82', 'Tarn-et-Garonne'), ('83', 'Var'),
    ('84', 'Vaucluse'), ('85', 'Vendée'), ('86', 'Vienne'), ('87', 'Haute-Vienne'),
    ('88', 'Vosges'), ('89', 'Yonne'), ('90', 'Territoire de Belfort'), ('91', 'Essonne'),
    ('92', 'Hauts-de-Seine'), ('93', 'Seine-Saint-Denis'), ('94', 'Val-de-Marne'), ('95', 'Val-d''Oise'),
    ('971', 'Guadeloupe'), ('972', 'Martinique'), ('973', 'Guyane'), ('974', 'La Réunion'),
    ('976', 'Mayotte');

INSERT INTO civilite (code, libelle, abreviation) VALUES
    ('M', 'Monsieur', 'M.'),
    ('MME', 'Madame', 'Mme'),
    ('ME', 'Maître', 'Me');
